FROM openjdk:8-jre-slim
LABEL autor="@omarnoriega"
		
RUN apt-get clean && \
    apt-get update && \
    apt-get -qy install \
    wget \
    telnet \
    iputils-ping \
    unzip \
    openssh-server \
    sudo \
    vim

#RUN useradd -rm -d /home/usuario -s /bin/bash -g root -G sudo -u 1000 usuario 
#RUN echo 'usuario:usuario' | chpasswd

RUN service ssh start
EXPOSE 22
CMD ["/usr/sbin/sshd","-D"]

ARG JMETER_VERSION=5.4.1

RUN mkdir /jmeter \
&& cd /jmeter/ \
&& wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-$JMETER_VERSION.tgz \
&& tar -xzf apache-jmeter-$JMETER_VERSION.tgz \
&& rm apache-jmeter-$JMETER_VERSION.tgz

COPY lib.zip /jmeter/apache-jmeter-$JMETER_VERSION/bin
RUN cd /jmeter/apache-jmeter-$JMETER_VERSION/bin \
    && unzip -o lib.zip \
    && rm lib.zip

ENV JMETER_HOME /jmeter/apache-jmeter-5.4.1/
ENV PATH $JMETER_HOME/bin:$PATH

RUN cd / && mkdir /jmx
COPY request-get.jmx /jmx
