FROM openjdk:8-jre-slim
LABEL autor="@omarnoriega"
		
RUN apt-get clean && \
    apt-get update && \
    apt-get -qy install \
    wget \
    telnet \
    iputils-ping \
    unzip \
    openssh-server \
    sudo \
    vim

#RUN useradd -rm -d /home/usuario -s /bin/bash -g root -G sudo -u 1000 usuario 
#RUN echo 'usuario:usuario' | chpasswd

RUN service ssh start
EXPOSE 22
CMD ["/usr/sbin/sshd","-D"]

RUN cd / && mkdir /jmeter
COPY apache-jmeter-5.4.1.zip /jmeter
RUN cd /jmeter/ \
    && unzip apache-jmeter-5.4.1.zip \
    && rm apache-jmeter-5.4.1.zip

RUN chmod +x /jmeter/apache-jmeter-5.4.1/bin/jmeter

ENV JMETER_HOME /jmeter/apache-jmeter-5.4.1/
ENV PATH $JMETER_HOME/bin:$PATH

RUN cd / && mkdir /jmx
COPY docs/request-get-erp.jmx /jmx
COPY docs/request-get.jmx /jmx