##################
# Master ConfigMap
##################
apiVersion: v1
kind: ConfigMap
metadata:
  name: jmeter-5-4-1-config
  labels:
    app: jmeter-5-4-1
data:
  load_test: |
    #!/bin/bash
    #Script created to invoke jmeter test script
    #Script should be run like: ./load_test "path to the test script in jmx format"
    /jmeter/apache-jmeter-5.4.1/bin/jmeter -n -t $1 -l /jmx/access.log

---
#######################
# Master Deployment
#######################
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: jmeter-5-4-1
  labels:
    app: jmeter-5-4-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jmeter-5-4-1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jmeter-5-4-1 
    spec:
      containers:
      - name: jmeter-5-4-1
        image: noriegadocker/jmeter-full:alpha
        ports:
        - containerPort: 22
        env:
        - name: TZ
          value: "America/Bogota"  
        volumeMounts:
        - name: jmeter-5-4-1-volume
          mountPath: /load_test
          subPath: "load_test"  
      volumes:
      - name: jmeter-5-4-1-volume
        configMap:
         name: jmeter-5-4-1-config